services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: ams-backend
    env_file:
      - ./backend/.env
    restart: unless-stopped
    ports:
      - "7001:7001"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: ams-frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
    restart: unless-stopped
